"""Generate Colab notebooks from extraction settings."""

from copy import deepcopy
from dataclasses import dataclass, field
import json
from pathlib import Path


TEMPLATE_PATH = Path(__file__).resolve().parents[2] / "colab" / "mwtn_notebook.ipynb"


@dataclass
class NotebookSettings:
    """Settings injected into a generated extraction notebook."""

    job_id: str
    song_title: str
    backend_url: str
    source_url: str = ""
    source_path: str = ""
    demucs_model: str = "htdemucs_6s"
    stems: list[str] = field(
        default_factory=lambda: ["vocals", "bass", "guitar", "piano", "drums", "other"]
    )
    enable_whisper: bool = True
    whisper_model: str = "small"
    whisper_language: str = "auto"
    enable_alignment: bool = True
    enable_notes: bool = True
    note_confidence: float = 0.6
    note_min_dur: float = 0.1
    enable_chords: bool = True
    enable_solfa: bool = True
    solfa_system: str = "movable_do"
    solfa_minor: str = "la_based"
    quantize_grid: int = 16
    enable_beaming: bool = True
    enable_confidence: bool = True
    confidence_threshold: float = 0.15
    enable_midi: bool = True
    enable_musicxml: bool = True
    enable_click_track: bool = True


def generate_notebook(settings: NotebookSettings) -> bytes:
    """Return a template notebook with the extraction parameters injected."""
    template = json.loads(TEMPLATE_PATH.read_text(encoding="utf-8"))
    notebook = deepcopy(template)
    params_cell = _find_params_cell(notebook)
    if params_cell is None:
        raise ValueError("Template notebook has no cell tagged 'parameters'")

    params_cell["source"] = _render_params_cell(settings)
    return json.dumps(notebook, indent=1, ensure_ascii=False).encode("utf-8")


def _find_params_cell(notebook: dict) -> dict | None:
    """Find the notebook cell tagged for generated parameters."""
    for cell in notebook.get("cells", []):
        if "parameters" in cell.get("metadata", {}).get("tags", []):
            return cell
    return None


def _python_string(value: str) -> str:
    """Render a user string as a safely quoted Python string literal."""
    return json.dumps(value, ensure_ascii=False)


def _render_params_cell(settings: NotebookSettings) -> list[str]:
    """Render source lines for the generated parameters cell."""
    s = settings
    lines = [
        "# ═══════════════════════════════════════════════════════\n",
        "# MWTN — Auto-generated parameters. Do not edit manually.\n",
        "# Generated by MWTN extract panel. Re-generate to change.\n",
        "# ═══════════════════════════════════════════════════════\n",
        "\n",
        f"JOB_ID        = {_python_string(s.job_id)}\n",
        f"SONG_TITLE    = {_python_string(s.song_title)}\n",
        'BACKEND_URL   = ""  # ← Paste your ngrok URL here before running\n',
        f"SOURCE_URL    = {_python_string(s.source_url)}\n",
        f"SOURCE_PATH   = {_python_string(s.source_path)}\n",
        "\n",
        f"DEMUCS_MODEL  = {_python_string(s.demucs_model)}\n",
        f"STEMS         = {json.dumps(s.stems, ensure_ascii=False)}\n",
        "\n",
        f"ENABLE_WHISPER    = {s.enable_whisper}\n",
        f"WHISPER_MODEL     = {_python_string(s.whisper_model)}\n",
        f"WHISPER_LANGUAGE  = {_python_string(s.whisper_language)}\n",
        f"ENABLE_ALIGNMENT  = {s.enable_alignment}\n",
        "\n",
        f"ENABLE_NOTES      = {s.enable_notes}\n",
        f"NOTE_CONFIDENCE   = {s.note_confidence}\n",
        f"NOTE_MIN_DUR      = {s.note_min_dur}\n",
        f"ENABLE_CHORDS     = {s.enable_chords}\n",
        "\n",
        f"ENABLE_SOLFA      = {s.enable_solfa}\n",
        f"SOLFA_SYSTEM      = {_python_string(s.solfa_system)}\n",
        f"SOLFA_MINOR       = {_python_string(s.solfa_minor)}\n",
        f"QUANTIZE_GRID     = {s.quantize_grid}\n",
        f"ENABLE_BEAMING    = {s.enable_beaming}\n",
        "\n",
        f"ENABLE_CONFIDENCE      = {s.enable_confidence}\n",
        f"CONFIDENCE_THRESHOLD   = {s.confidence_threshold}\n",
        "\n",
        f"ENABLE_MIDI        = {s.enable_midi}\n",
        f"ENABLE_MUSICXML    = {s.enable_musicxml}\n",
        f"ENABLE_CLICK_TRACK = {s.enable_click_track}\n",
    ]
    return lines
